"""研究ノートブック生成。分析結果をMarkdown形式で自動生成する。"""
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def generate_research_notebook(
    title: str,
    sections: list[dict],
    metadata: dict | None = None,
) -> str:
    """Markdown 形式の研究ノートブックを生成する。

    Args:
        title: ノートブックタイトル
        sections: [{"heading": str, "content": str, "data": dict|None}, ...]
        metadata: メタデータ
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# {title}",
        f"",
        f"**Generated:** {now}",
        f"**System:** QuakeMind Autonomous Research Agent",
        f"",
    ]

    if metadata:
        lines.append("## Metadata")
        lines.append("")
        for k, v in metadata.items():
            lines.append(f"- **{k}:** {v}")
        lines.append("")

    lines.append("---")
    lines.append("")

    for i, section in enumerate(sections, 1):
        heading = section.get("heading", f"Section {i}")
        content = section.get("content", "")
        data = section.get("data")

        lines.append(f"## {i}. {heading}")
        lines.append("")

        if content:
            lines.append(content)
            lines.append("")

        if data:
            if isinstance(data, dict):
                lines.append("```json")
                import json
                lines.append(json.dumps(data, ensure_ascii=False, indent=2)[:2000])
                lines.append("```")
            elif isinstance(data, list):
                for item in data[:20]:
                    lines.append(f"- {item}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Auto-generated by QuakeMind Research Agent*")

    return "\n".join(lines)


def generate_daily_notebook(analyses: dict) -> str:
    """日次分析結果からノートブックを生成する。"""
    sections = []

    if "anomaly" in analyses:
        a = analyses["anomaly"]
        sections.append({
            "heading": "異常活動検知",
            "content": f"異常検出: {'はい' if a.get('is_anomalous') else 'いいえ'} (p={a.get('p_value', 'N/A')})",
            "data": a,
        })

    if "b_value" in analyses:
        sections.append({
            "heading": "b値追跡",
            "content": f"最新b値: {analyses['b_value'].get('b_value_latest', 'N/A')}",
            "data": analyses["b_value"],
        })

    if "clusters" in analyses:
        c = analyses["clusters"]
        sections.append({
            "heading": "クラスタリング",
            "content": f"{c.get('n_clusters', 0)}個のクラスタを検出",
            "data": c,
        })

    if not sections:
        sections.append({"heading": "概要", "content": "本日の分析データなし"})

    return generate_research_notebook(
        f"QuakeMind 日次研究ノート ({datetime.now(timezone.utc).strftime('%Y-%m-%d')})",
        sections,
        metadata={"type": "daily", "n_analyses": len(sections)},
    )
